---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure load balancing
  template:
    src: load-balancer.conf.j2
    dest: /etc/nginx/conf.d/load-balancer.conf

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes